general:
  seed: 42

wandb:
  api_key: ""
  project: "ViTUnified-PAD"

model:
  model_name: "vit_small_patch16_224"
  pretrained: false
  num_classes: 2
  pad_dropout: 0.0
  recog_ckpt: "ckpts/recog/best_model.pth"

optimizer:
  lr: 1.0e-4
  weight_decay: 2.0e-5
  
scheduler:
  power: 3
  min_lr: 1.0e-5

training:
  epochs: 30
  batch_size: 256
  num_workers: 8
  pin_memory: true
  checkpoint_interval: 10

loss:
  lambda_mse: 1.0

data:
  split_path: "data/LivDet/livdet_pad_splits.json"

output:
  checkpoint_dir: "ckpts/pad/"
  best_model_name: "best_model.pth"

evaluation:
  batch_size: 256
  num_workers: 8
  pin_memory: true
  checkpoint_path: "ckpts/pad/best_model.pth"